#!/bin/bash

# TASK 1
# fist line is called as shebang and its distinguish the shell


# TASK 2
echo "this is my first day of task as a beginner."



# TASK 3
country="INDIA"
state="ODISHA"



#TASK 4
number1="22"
number2="22"
sum=$((number1+number2))
echo "the sum of: $sum"


#TASK 5
echo "which operating system: $OSTYPE"
echo "host name: $HOSTNAME"
echo "display the home directory: $HOME"
echo "display the shell name: $BASH"
echo "display the languge: $LANG"

#TASK 6
echo "show all the file exist:"
ls *.txt

#happy scriptings

